cacheFolder: ./.yarn/cache

checksumBehavior: update

cloneConcurrency: 1

compressionLevel: mixed

enableGlobalCache: false

networkConcurrency: 1

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
